jobs_board/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jobs
  root 'jobs#index'
end

jobs_board/app/models/application_record.rb
# apalication_record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

jobs_board/app/models/category.rb
# Category model
class Category < ApplicationRecord
  has_many :jobs
end

jobs_board/app/models/job.rb
# Jobs model
class Job < ApplicationRecord
  belongs_to :category
  belongs_to :user
end

jobs_board/app/models/user.rb
# User model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :jobs
end

jobs_board/app/controllers/application_controller.rb
# application controller
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

jobs_board/app/controllers/jobs_controller.rb
# jobs controller
class JobsController < ApplicationController
  before_action :find_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    if params[:category].blank?
      @jobs = Job.all.order('Created_at DESC')
    else
      @category_id = Category.find_by(name: params[:category]).id
      @jobs = Job.where(category_id: @category_id).order('Created_at DESC')
    end
  end

  def show
  end

  def new
    # @job = Job.new
    @job = current_user.jobs.build
  end

  def create
    @job = current_user.jobs.build(jobs_params)
    # @job = Job.new(jobs_params)
    if @job.save
      redirect_to @job
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @job.update(jobs_params)
      redirect_to @job
    else
      render 'edit'
    end
  end

  def destroy
    @job.destroy
    redirect_to root_path
  end

  private

  def jobs_params
    params.require(:job).permit(:title, :description, :company, :url, :category_id)
  end

  def find_job
    @job = Job.find(params[:id])
  end
end

jobs_board/app/helpers/application_helper.rb
# application helper
module ApplicationHelper
end

jobs_board/app/helpers/jobs_helper.rb
# jobshelper
module JobsHelper
end

jobs_board/app/views/jobs/_form.html.erb
<!-- <div class = "container">
	<div class="col-md-6"> -->
		<%= simple_form_for(@job, html: { class: 'form-horizontal'}) do |f| %>
			<%= f.collection_select :category_id, Category.all, :id, :name,
														  { promt: "Choose a category"}, input_html: { class: "form-control"} %>
			<%=	f.input :title, label: "Job Title" %>
			<%=	f.input :description, label: "job Description" %>
			<%=	f.input :company, label: "Company" %>
			<%=	f.input :url, label: "Link to job" %>
		  <%= f.button :submit %>
		<% end %>
	<!-- /div>
	<div class="col-md-6">
	</div>
</div> -->

jobs_board/app/views/jobs/edit.html.erb
<h1>  Edit Job</h1>
<div class="row">
	<%= render 'form' %>
</div>	
<%= link_to 'Back', root_path	%>

jobs_board/app/views/jobs/index.html.erb
<% @jobs.each do |job|%>
<h2><%= link_to job.title, job%></h2>
<p><%= link_to job.company, job %></p>
<% end %>

jobs_board/app/views/jobs/new.html.erb
<h1>  New Job</h1>
<div class="row">
	<%= render 'form' %>
	</div>
<%= link_to 'Back', root_path	%>

jobs_board/app/views/jobs/show.html.erb
<div class = "jobs">
	<h1><%= @job.title %></h1>
	<p><%= @job.description%></p>
	<p><%= @job.company%></p>
	<button type="button" class="btn btn-default">
		<%= link_to 'Apply for job', @job.url%>
	</button>
</div>
<div class = "links">
	<button type="button" class="btn-sm btn-default"><%= link_to 'Home', root_path %></button>
	<button type="button" class="btn-sm btn-default"><%= link_to 'Edit', edit_job_path(@job) %></button>
	<button type="button" class="btn-sm btn-default"><%= link_to 'Delete', job_path(@job),
	    method: :delete, data: { confirm: 'Are you sure?' }, class: "btn.btn-sm btn-default" %>
	</button>
</div>

jobs_board/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobsBoard</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <div class="navbar navbar-default">
	  	<div class="container">

		    <ul class="nav navbar-nav">
			    <li> <%=link_to 'All Jobs', root_path %></li>
			  	<% Category.all.each do |category|%>
			  	<li><%= link_to category.name, jobs_path(category: category.name)%></li>
			  	<% end %>
			  </ul>
			 	<%= link_to "New Job", new_job_path, class: "navbar-text navbar-right navbar-link"%>
	    </div>
	  </div>
	  <div class="container">
		  <div class="col-md-6 col-offset-3">
		  	<p class="notice"><%= notice %></p>
       	<p class="alert"><%= alert %></p>
       	<%= link_to "Sign_Up", new_user_registration_path %>
       	<%= link_to "Sign_In", new_user_session_path %>
       	<%= link_to 'Sign_out', destroy_user_session_path(@user), method: :delete, data: { confirm: 'Are you sure?' } %>
		  	<%= yield %>
	  	</div>
	  </div>
  </body>
</html>